version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: inventory_manager
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory
      SPRING_DATASOURCE_USERNAME: dev
      SPRING_DATASOURCE_PASSWORD: dev123
    command: ["java", "-jar", "app.jar"]

volumes:
  pgdata: